/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"

#include "MainComponent.h"

class KentDawWindow  : public DocumentWindow
{
public:
    //==============================================================================
    KentDawWindow()
    : DocumentWindow (("UKC Digital Audio Workstation"),
                      Colours::darkgrey,
                      DocumentWindow::allButtons,
                      true)
    {
        // Create an instance of our main content component, and add it
        // to our window.
        
        MainComponent* contentComponent = new MainComponent();
        
        contentComponent->setSize(getWidth(), getHeight());
        setContentComponent(contentComponent, true, true);
        setFullScreen(true);
        setResizable(true, false);
        
        setVisible (true);
    }
    
    ~KentDawWindow()
    {
        // (the content component will be deleted automatically, so no need to do it here)
    }
    
    //==============================================================================
    void closeButtonPressed()
    {
        // When the user presses the close button, we'll tell the app to quit. This
        // window will be deleted by our HelloWorldApplication::shutdown() method
        //
        JUCEApplication::quit();
    }
};

//==============================================================================
class KentDAWApplication  : public JUCEApplication
{
    KentDawWindow* kentDawWindow;

public:
    //==============================================================================
    KentDAWApplication()
    :kentDawWindow(0){}

    const String getApplicationName() override       { return ProjectInfo::projectName; }
    const String getApplicationVersion() override    { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed() override       { return true; }

    //==============================================================================
    void initialise (const String& commandLine) override
    {
        // Add your application's initialisation code here..
        kentDawWindow = new KentDawWindow();
    }

    void shutdown() override
    {
        // Add your application's shutdown code here..
        if (kentDawWindow != 0)
            delete kentDawWindow;
    }

    //==============================================================================
    void systemRequestedQuit() override
    {
        // This is called when the app is being asked to quit: you can ignore this
        // request and let the app carry on running, or call quit() to allow the app to close.
        quit();
    }

    void anotherInstanceStarted (const String& commandLine) override
    {
        // When another instance of the app is launched while this one is running,
        // this method is invoked, and the commandLine parameter tells you what
        // the other instance's command-line arguments were.
    }
};


//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (KentDAWApplication)
